export const planetsVisualData = [
  {
    id: 1,
    planetName: "earth",
    textureUrl: "/earth.jpg",
    distance: 45,
    radius: 3,
    speed: 0.3,
    rotationSpeed: 0.42,
  },
  {
    id: 2,
    planetName: "mercury",
    textureUrl: "/mercury.jpg",
    distance: 20,
    radius: 1,
    speed: 0.47,
    rotationSpeed: 0.071,
  },
  {
    id: 3,
    planetName: "jupiter",
    textureUrl: "/jupiter.jpg",
    distance: 80,
    radius: 7.15,
    speed: 0.13,
    rotationSpeed: 1,
  },
  {
    id: 4,
    planetName: "mars",
    textureUrl: "/mars.jpg",
    distance: 60,
    radius: 1.5,
    speed: 0.24,
    rotationSpeed: 0.41,
  },
  {
    id: 5,
    planetName: "saturn",
    textureUrl: "/saturn.jpg",
    distance: 100,
    radius: 7,
    speed: 0.097,
    rotationSpeed: 0.95,
  },
  {
    id: 6,
    planetName: "neptune",
    textureUrl: "/neptune.jpg",
    distance: 150,
    radius: 5,
    speed: 0.054,
    rotationSpeed: 0.625,
  },
  {
    id: 7,
    planetName: "uranus",
    textureUrl: "/uranus.jpg",
    distance: 125,
    radius: 5.1,
    speed: 0.068,
    rotationSpeed: 0.58,
  },
  {
    id: 8,
    planetName: "venus",
    textureUrl: "/venus.jpg",
    distance: 30,
    radius: 2.9,
    speed: 0.35,
    rotationSpeed: 0.017,
  },
];

export const planetsRealData = [
  {
    id: 9,
    planetName: "earth",
    distance: "150.196.428",
    radius: "6.378",
    mass: "5.9722",
    massPow: "24",
    tempC: "15",
    tempF: "57.2",
    gravity: "9.8",
    description:
      "Earth is the third planet from the Sun and the only astronomical object known to harbor life. This is made possible by Earth being an ocean world, the only one in the Solar System sustaining liquid surface water. Almost all of Earth's water is contained in its ocean, which covers 70.8% of Earth's crust. The remaining 29.2% of Earth's crust is land, which is predominantly located within Earth's land hemisphere in the form of continental landmasses. Most of Earth's land is at least somewhat humid and covered by vegetation, while large ice sheets at Earth's polar deserts retain more water than Earth's groundwater, lakes, rivers, and atmospheric water combined. Earth's crust consists of slowly moving tectonic plates, which interact to produce mountain ranges, volcanoes, and earthquakes. Earth has a liquid outer core that generates a magnetosphere capable of deflecting most of the destructive solar winds and cosmic radiation.",
  },

  {
    id: 10,
    planetName: "mercury",
    distance: "58.726.000",
    radius: "2.440",
    mass: "3.3011",
    massPow: "23",
    tempC: "167",
    tempF: "333",
    gravity: "3.7",
    description:
      "Mercury is the first planet from the Sun and the smallest in the Solar System. It is a rocky planet with a trace atmosphere and a surface gravity slightly lower than that of Mars. The surface of Mercury is similar to Earth's Moon, being cratered, with an expansive rupes system generated from thrust faults, and bright ray systems, formed by ejecta. Its largest crater, Caloris Planitia, has a diameter of 1,550 km (960 mi), which is about one-third the diameter of the planet (4,880 km or 3,030 mi). Being the most inferior orbiting planet, it always appears close to the Sun in Earth's sky, as either a <morning star> or an <evening star>. It is the planet with the highest delta-v required for travel from Earth, as well as to and from the other planets in the Solar System.",
  },
  {
    id: 11,
    planetName: "jupiter",
    distance: "483 million",
    radius: "69.911",
    mass: "1.9",
    massPow: "27",
    tempC: "-110",
    tempF: "-166",
    gravity: "24.5",
    description:
      "Jupiter is the fifth planet from the Sun, and the largest in the Solar System. It is a gas giant with a mass nearly 2.5 times that of all the other planets in the Solar System combined and slightly less than one-thousandth the mass of the Sun. The diameter of Jupiter is 11 times that of Earth and a tenth that of the Sun. It orbits the Sun at a distance of 5.20 AU (778.5 Gm), with an orbital period of 11.86 years. Jupiter is the third-brightest natural object in the Earth's night sky, after the Moon and Venus, and has been observed since prehistoric times. Its name derives from that of Jupiter, the chief deity of ancient Roman religion.",
  },
  {
    id: 12,
    planetName: "mars",
    distance: "228 million",
    radius: "3.390",
    mass: "6.42",
    massPow: "23",
    tempC: "-65",
    tempF: "-85",
    gravity: "3.7",
    description:
      "Mars is the fourth planet from the Sun. It is also known as the <Red Planet>, for its orange-red appearance. Mars is a desert-like rocky planet with a tenuous atmosphere that is primarily carbon dioxide (CO2). At the average surface level the atmospheric pressure is a few thousandths of Earth's, atmospheric temperature ranges from -153 to 20 °C (-243 to 68 °F), and cosmic radiation is high. Mars retains some water, in the ground as well as thinly in the atmosphere, forming cirrus clouds, fog, frost, larger polar regions of permafrost and ice caps (with seasonal CO2 snow), but no bodies of liquid surface water. Its surface gravity is roughly a third of Earth's or double that of the Moon. Its mean diameter, 6,779 km (4,212 mi), is about half the Earth's, or twice the Moon's, and its surface area is the size of all the dry land of Earth.",
  },
  {
    id: 13,
    planetName: "saturn",
    distance: "886 million",
    radius: "60.268",
    mass: "5.68",
    massPow: "26",
    tempC: "-140",
    tempF: "-220",
    gravity: "10.44",
    description:
      "Saturn is the sixth planet from the Sun and the second largest in the Solar System, after Jupiter. It is a gas giant, with an average radius of about 9 times that of Earth. It has an eighth of the average density of Earth, but is over 95 times more massive. Even though Saturn is almost as big as Jupiter, it has less than a third of its mass. Saturn orbits the Sun at a distance of 9.59 AU (1,434 million km), with an orbital period of 29.45 years.",
  },
  {
    id: 14,
    planetName: "neptune",
    distance: "2.8 billion",
    radius: "24.622",
    mass: "1.024",
    massPow: "26",
    tempC: "-200",
    tempF: "-330",
    gravity: "11.15",
    description:
      "Neptune is the eighth and farthest known planet orbiting the Sun. It is the fourth-largest planet in the Solar System by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth. Compared to Uranus, its neighbouring ice giant, Neptune is slightly smaller, but more massive and dense. Being composed primarily of gases and liquids, it has no well-defined solid surface. Neptune orbits the Sun once every 164.8 years at an orbital distance of 30.1 astronomical units (4.5 billion kilometres; 2.8 billion miles). It is named after the Roman god of the sea and has the astronomical symbol ♆, representing Neptune's trident.",
  },
  {
    id: 15,
    planetName: "uranus",
    distance: "2.9 billion",
    radius: "25.559",
    mass: "8.682",
    massPow: "25",
    tempC: "-195",
    tempF: "-320",
    gravity: "8.69",
    description:
      "Uranus is the seventh planet from the Sun. It is a gaseous cyan-coloured ice giant. Most of the planet is made of water, ammonia, and methane in a supercritical phase of matter, which astronomy calls <ice> or volatiles. The planet's atmosphere has a complex layered cloud structure and has the lowest minimum temperature (49 K (-224 °C; -371 °F)) of all the Solar System's planets. It has a marked axial tilt of 82.23° with a retrograde rotation period of 17 hours and 14 minutes. This means that in an 84-Earth-year orbital period around the Sun, its poles get around 42 years of continuous sunlight, followed by 42 years of continuous darkness.",
  },
  {
    id: 16,
    planetName: "venus",
    distance: "108 million",
    radius: "6.052",
    mass: "4.868",
    massPow: "24",
    tempC: "464",
    tempF: "867",
    gravity: "8.87",
    description:
      "Venus is the second planet from the Sun. Similar in size and mass to Earth, Venus has no liquid water, and its atmosphere is far thicker and denser than that of any other rocky body in the Solar System. The atmosphere is composed mostly of carbon dioxide and has a thick cloud layer of sulfuric acid that spans the whole planet. At the mean surface level, the atmosphere reaches a temperature of 737 K (464 °C; 867 °F), making it the hottest planet in the solar system and also a pressure 92 times greater than Earth's at sea level, turning the lowest layer of the atmosphere into a supercritical fluid. From Earth, Venus is visible as a star-like point of light, appearing brighter than any other natural point of light in the sky, as either the brightest <morning star> or <evening star>. It was also given the poetic name Ēarendel in Old English, meaning <ray of light> along with the two previous epithets.",
  },
];
